[package]
name = "enclave"
version = "0.1.0"
edition = "2021"

[lib]
name = "pobfref"
crate-type = ["lib", "staticlib"]

[features]
# turn on mirai when veirifying towards mirai
default = []
sgx = ["sgx_tstd", "sgx_trts", "sgx_rand", "sgx_tseal", "sgx_tcrypto"]
# potential violations
violation = ["vio_typestate", "vio_private", "vio_unsafe"]
vio_typestate = []
vio_private = []
vio_unsafe = []

[dependencies]
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
mirai-annotations = { path = "../../MIRAI/annotations" }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", default-features = false, optional = true }
sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git", default-features = false, optional = true }
sgx_rand = { git = "https://github.com/apache/teaclave-sgx-sdk.git", default-features = false, optional = true }
sgx_tseal = { git = "https://github.com/apache/teaclave-sgx-sdk.git", default-features = false, optional = true }
sgx_tcrypto = { git = "https://github.com/apache/teaclave-sgx-sdk.git", default-features = false, optional = true }
