[package]
name = "enclave"
version = "0.1.0"
edition = "2021"

[lib]
name = "pobfref"
crate-type = ["lib", "staticlib"]

[features]
# turn on mirai when veirifying towards mirai
default = ["sgx"]
sgx = ["sgx_tstd", "sgx_trts", "sgx_rand", "sgx_tseal", "sgx_crypto"]
# potential violations
violation = ["vio_typestate", "vio_private", "vio_unsafe"]
vio_typestate = []
vio_private = []
vio_unsafe = []

# [dependencies]
# sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "v2.0.0-preview"}
# mirai-annotations = { path = "../../MIRAI/annotations" }
# sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "v2.0.0-preview", optional = true }
# sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "v2.0.0-preview", optional = true }
# sgx_rand = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "v2.0.0-preview", optional = true }
# sgx_tseal = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "v2.0.0-preview", optional = true }
# sgx_crypto = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "v2.0.0-preview", optional = true }
# # sgx_crypto_sys = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "v2.0.0-preview" }

[dependencies]
sgx_types = { path = "../incubator-teaclave-sgx-sdk/sgx_types"}
mirai-annotations = { path = "../../MIRAI/annotations" }
sgx_tstd = { path = "../incubator-teaclave-sgx-sdk/sgx_tstd", optional = true }
sgx_trts = { path = "../incubator-teaclave-sgx-sdk/sgx_trts", optional = true }
sgx_rand = { path = "../incubator-teaclave-sgx-sdk/sgx_rand", optional = true }
sgx_tseal = { path = "../incubator-teaclave-sgx-sdk/sgx_tseal", optional = true }
sgx_crypto = { path = "../incubator-teaclave-sgx-sdk/sgx_crypto", optional = true }
# sgx_crypto_sys = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "v2.0.0-preview" }
