includes:
  - base.yaml
targets:
  - target: /bin
    copy:
      - files:
        - ./rust_app/target/x86_64-unknown-linux-musl/release/server
        - ./rust_app/target/x86_64-unknown-linux-musl/release/client
